INSERT INTO country VALUES (1, 'United States');
INSERT INTO country VALUES (2, 'Canada');
INSERT INTO country VALUES (3, 'Afghanistan');
INSERT INTO country VALUES (4, 'Albania');
INSERT INTO country VALUES (5, 'Algeria');
INSERT INTO country VALUES (6, 'American Samoa');
INSERT INTO country VALUES (7, 'Andorra');
INSERT INTO country VALUES (8, 'Angola');
INSERT INTO country VALUES (9, 'Anguilla');
INSERT INTO country VALUES (10, 'Antarctica');
INSERT INTO country VALUES (11, 'Antigua and/or Barbuda');
INSERT INTO country VALUES (12, 'Argentina');
INSERT INTO country VALUES (13, 'Armenia');
INSERT INTO country VALUES (14, 'Aruba');
INSERT INTO country VALUES (15, 'Australia');
INSERT INTO country VALUES (16, 'Austria');
INSERT INTO country VALUES (17, 'Azerbaijan');
INSERT INTO country VALUES (18, 'Bahamas');
INSERT INTO country VALUES (19, 'Bahrain');
INSERT INTO country VALUES (20, 'Bangladesh');
INSERT INTO country VALUES (21, 'Barbados');
INSERT INTO country VALUES (22, 'Belarus');
INSERT INTO country VALUES (23, 'Belgium');
INSERT INTO country VALUES (24, 'Belize');
INSERT INTO country VALUES (25, 'Benin');
INSERT INTO country VALUES (26, 'Bermuda');
INSERT INTO country VALUES (27, 'Bhutan');
INSERT INTO country VALUES (28, 'Bolivia');
INSERT INTO country VALUES (29, 'Bosnia and Herzegovina');
INSERT INTO country VALUES (30, 'Botswana');
INSERT INTO country VALUES (31, 'Bouvet Island');
INSERT INTO country VALUES (32, 'Brazil');
INSERT INTO country VALUES (33, 'British lndian Ocean Territory');
INSERT INTO country VALUES (34, 'Brunei Darussalam');
INSERT INTO country VALUES (35, 'Bulgaria');
INSERT INTO country VALUES (36, 'Burkina Faso');
INSERT INTO country VALUES (37, 'Burundi');
INSERT INTO country VALUES (38, 'Cambodia');
INSERT INTO country VALUES (39, 'Cameroon');
INSERT INTO country VALUES (40, 'Cape Verde');
INSERT INTO country VALUES (41, 'Cayman Islands');
INSERT INTO country VALUES (42, 'Central African Republic');
INSERT INTO country VALUES (43, 'Chad');
INSERT INTO country VALUES (44, 'Chile');
INSERT INTO country VALUES (45, 'China');
INSERT INTO country VALUES (46, 'Christmas Island');
INSERT INTO country VALUES (47, 'Cocos (Keeling) Islands');
INSERT INTO country VALUES (48, 'Colombia');
INSERT INTO country VALUES (49, 'Comoros');
INSERT INTO country VALUES (50, 'Congo');
INSERT INTO country VALUES (51, 'Cook Islands');
INSERT INTO country VALUES (52, 'Costa Rica');
INSERT INTO country VALUES (53, 'Croatia (Hrvatska)');
INSERT INTO country VALUES (54, 'Cuba');
INSERT INTO country VALUES (55, 'Cyprus');
INSERT INTO country VALUES (56, 'Czech Republic');
INSERT INTO country VALUES (57, 'Denmark');
INSERT INTO country VALUES (58, 'Djibouti');
INSERT INTO country VALUES (59, 'Dominica');
INSERT INTO country VALUES (60, 'Dominican Republic');
INSERT INTO country VALUES (61, 'East Timor');
INSERT INTO country VALUES (62, 'Ecuador');
INSERT INTO country VALUES (63, 'Egypt');
INSERT INTO country VALUES (64, 'El Salvador');
INSERT INTO country VALUES (65, 'Equatorial Guinea');
INSERT INTO country VALUES (66, 'Eritrea');
INSERT INTO country VALUES (67, 'Estonia');
INSERT INTO country VALUES (68, 'Ethiopia');
INSERT INTO country VALUES (69, 'Falkland Islands (Malvinas)');
INSERT INTO country VALUES (70, 'Faroe Islands');
INSERT INTO country VALUES (71, 'Fiji');
INSERT INTO country VALUES (72, 'Finland');
INSERT INTO country VALUES (73, 'France');
INSERT INTO country VALUES (74, 'France, Metropolitan');
INSERT INTO country VALUES (75, 'French Guiana');
INSERT INTO country VALUES (76, 'French Polynesia');
INSERT INTO country VALUES (77, 'French Southern Territories');
INSERT INTO country VALUES (78, 'Gabon');
INSERT INTO country VALUES (79, 'Gambia');
INSERT INTO country VALUES (80, 'Georgia');
INSERT INTO country VALUES (81, 'Germany');
INSERT INTO country VALUES (82, 'Ghana');
INSERT INTO country VALUES (83, 'Gibraltar');
INSERT INTO country VALUES (84, 'Greece');
INSERT INTO country VALUES (85, 'Greenland');
INSERT INTO country VALUES (86, 'Grenada');
INSERT INTO country VALUES (87, 'Guadeloupe');
INSERT INTO country VALUES (88, 'Guam');
INSERT INTO country VALUES (89, 'Guatemala');
INSERT INTO country VALUES (90, 'Guinea');
INSERT INTO country VALUES (91, 'Guinea-Bissau');
INSERT INTO country VALUES (92, 'Guyana');
INSERT INTO country VALUES (93, 'Haiti');
INSERT INTO country VALUES (94, 'Heard and Mc Donald Islands');
INSERT INTO country VALUES (95, 'Honduras');
INSERT INTO country VALUES (96, 'Hong Kong');
INSERT INTO country VALUES (97, 'Hungary');
INSERT INTO country VALUES (98, 'Iceland');
INSERT INTO country VALUES (99, 'India');
INSERT INTO country VALUES (100, 'Indonesia');
INSERT INTO country VALUES (101, 'Iran (Islamic Republic of)');
INSERT INTO country VALUES (102, 'Iraq');
INSERT INTO country VALUES (103, 'Ireland');
INSERT INTO country VALUES (104, 'Israel');
INSERT INTO country VALUES (105, 'Italy');
INSERT INTO country VALUES (106, 'Ivory Coast');
INSERT INTO country VALUES (107, 'Jamaica');
INSERT INTO country VALUES (108, 'Japan');
INSERT INTO country VALUES (109, 'Jordan');
INSERT INTO country VALUES (110, 'Kazakhstan');
INSERT INTO country VALUES (111, 'Kenya');
INSERT INTO country VALUES (112, 'Kiribati');
INSERT INTO country VALUES (113, 'Korea, Democratic People''s Republic of');
INSERT INTO country VALUES (114, 'Korea, Republic of');
INSERT INTO country VALUES (115, 'Kosovo');
INSERT INTO country VALUES (116, 'Kuwait');
INSERT INTO country VALUES (117, 'Kyrgyzstan');
INSERT INTO country VALUES (118, 'Lao People''s Democratic Republic');
INSERT INTO country VALUES (119, 'Latvia');
INSERT INTO country VALUES (120, 'Lebanon');
INSERT INTO country VALUES (121, 'Lesotho');
INSERT INTO country VALUES (122, 'Liberia');
INSERT INTO country VALUES (123, 'Libyan Arab Jamahiriya');
INSERT INTO country VALUES (124, 'Liechtenstein');
INSERT INTO country VALUES (125, 'Lithuania');
INSERT INTO country VALUES (126, 'Luxembourg');
INSERT INTO country VALUES (127, 'Macau');
INSERT INTO country VALUES (128, 'Macedonia');
INSERT INTO country VALUES (129, 'Madagascar');
INSERT INTO country VALUES (130, 'Malawi');
INSERT INTO country VALUES (131, 'Malaysia');
INSERT INTO country VALUES (132, 'Maldives');
INSERT INTO country VALUES (133, 'Mali');
INSERT INTO country VALUES (134, 'Malta');
INSERT INTO country VALUES (135, 'Marshall Islands');
INSERT INTO country VALUES (136, 'Martinique');
INSERT INTO country VALUES (137, 'Mauritania');
INSERT INTO country VALUES (138, 'Mauritius');
INSERT INTO country VALUES (139, 'Mayotte');
INSERT INTO country VALUES (140, 'Mexico');
INSERT INTO country VALUES (141, 'Micronesia, Federated States of');
INSERT INTO country VALUES (142, 'Moldova, Republic of');
INSERT INTO country VALUES (143, 'Monaco');
INSERT INTO country VALUES (144, 'Mongolia');
INSERT INTO country VALUES (145, 'Montenegro');
INSERT INTO country VALUES (146, 'Montserrat');
INSERT INTO country VALUES (147, 'Morocco');
INSERT INTO country VALUES (148, 'Mozambique');
INSERT INTO country VALUES (149, 'Myanmar');
INSERT INTO country VALUES (150, 'Namibia');
INSERT INTO country VALUES (151, 'Nauru');
INSERT INTO country VALUES (152, 'Nepal');
INSERT INTO country VALUES (153, 'Netherlands');
INSERT INTO country VALUES (154, 'Netherlands Antilles');
INSERT INTO country VALUES (155, 'New Caledonia');
INSERT INTO country VALUES (156, 'New Zealand');
INSERT INTO country VALUES (157, 'Nicaragua');
INSERT INTO country VALUES (158, 'Niger');
INSERT INTO country VALUES (159, 'Nigeria');
INSERT INTO country VALUES (160, 'Niue');
INSERT INTO country VALUES (161, 'Norfork Island');
INSERT INTO country VALUES (162, 'Northern Mariana Islands');
INSERT INTO country VALUES (163, 'Norway');
INSERT INTO country VALUES (164, 'Oman');
INSERT INTO country VALUES (165, 'Pakistan');
INSERT INTO country VALUES (166, 'Palau');
INSERT INTO country VALUES (167, 'Panama');
INSERT INTO country VALUES (168, 'Papua New Guinea');
INSERT INTO country VALUES (169, 'Paraguay');
INSERT INTO country VALUES (170, 'Peru');
INSERT INTO country VALUES (171, 'Philippines');
INSERT INTO country VALUES (172, 'Pitcairn');
INSERT INTO country VALUES (173, 'Poland');
INSERT INTO country VALUES (174, 'Portugal');
INSERT INTO country VALUES (175, 'Puerto Rico');
INSERT INTO country VALUES (176, 'Qatar');
INSERT INTO country VALUES (177, 'Reunion');
INSERT INTO country VALUES (178, 'Romania');
INSERT INTO country VALUES (179, 'Russian Federation');
INSERT INTO country VALUES (180, 'Rwanda');
INSERT INTO country VALUES (181, 'Saint Kitts and Nevis');
INSERT INTO country VALUES (182, 'Saint Lucia');
INSERT INTO country VALUES (183, 'Saint Vincent and the Grenadines');
INSERT INTO country VALUES (184, 'Samoa');
INSERT INTO country VALUES (185, 'San Marino');
INSERT INTO country VALUES (186, 'Sao Tome and Principe');
INSERT INTO country VALUES (187, 'Saudi Arabia');
INSERT INTO country VALUES (188, 'Senegal');
INSERT INTO country VALUES (189, 'Serbia');
INSERT INTO country VALUES (190, 'Seychelles');
INSERT INTO country VALUES (191, 'Sierra Leone');
INSERT INTO country VALUES (192, 'Singapore');
INSERT INTO country VALUES (193, 'Slovakia');
INSERT INTO country VALUES (194, 'Slovenia');
INSERT INTO country VALUES (195, 'Solomon Islands');
INSERT INTO country VALUES (196, 'Somalia');
INSERT INTO country VALUES (197, 'South Africa');
INSERT INTO country VALUES (198, 'South Georgia South Sandwich Islands');
INSERT INTO country VALUES (199, 'Spain');
INSERT INTO country VALUES (200, 'Sri Lanka');
INSERT INTO country VALUES (201, 'St. Helena');
INSERT INTO country VALUES (202, 'St. Pierre and Miquelon');
INSERT INTO country VALUES (203, 'Sudan');
INSERT INTO country VALUES (204, 'Suriname');
INSERT INTO country VALUES (205, 'Svalbarn and Jan Mayen Islands');
INSERT INTO country VALUES (206, 'Swaziland');
INSERT INTO country VALUES (207, 'Sweden');
INSERT INTO country VALUES (208, 'Switzerland');
INSERT INTO country VALUES (209, 'Syrian Arab Republic');
INSERT INTO country VALUES (210, 'Taiwan');
INSERT INTO country VALUES (211, 'Tajikistan');
INSERT INTO country VALUES (212, 'Tanzania, United Republic of');
INSERT INTO country VALUES (213, 'Thailand');
INSERT INTO country VALUES (214, 'Togo');
INSERT INTO country VALUES (215, 'Tokelau');
INSERT INTO country VALUES (216, 'Tonga');
INSERT INTO country VALUES (217, 'Trinidad and Tobago');
INSERT INTO country VALUES (218, 'Tunisia');
INSERT INTO country VALUES (219, 'Turkey');
INSERT INTO country VALUES (220, 'Turkmenistan');
INSERT INTO country VALUES (221, 'Turks and Caicos Islands');
INSERT INTO country VALUES (222, 'Tuvalu');
INSERT INTO country VALUES (223, 'Uganda');
INSERT INTO country VALUES (224, 'Ukraine');
INSERT INTO country VALUES (225, 'United Arab Emirates');
INSERT INTO country VALUES (226, 'United Kingdom');
INSERT INTO country VALUES (227, 'United States minor outlying islands');
INSERT INTO country VALUES (228, 'Uruguay');
INSERT INTO country VALUES (229, 'Uzbekistan');
INSERT INTO country VALUES (230, 'Vanuatu');
INSERT INTO country VALUES (231, 'Vatican City State');
INSERT INTO country VALUES (232, 'Venezuela');
INSERT INTO country VALUES (233, 'Vietnam');
INSERT INTO country VALUES (234, 'Virigan Islands (British)');
INSERT INTO country VALUES (235, 'Virgin Islands (U.S.)');
INSERT INTO country VALUES (236, 'Wallis and Futuna Islands');
INSERT INTO country VALUES (237, 'Western Sahara');
INSERT INTO country VALUES (238, 'Yemen');
INSERT INTO country VALUES (239, 'Yugoslavia');
INSERT INTO country VALUES (240, 'Zaire');
INSERT INTO country VALUES (241, 'Zambia');
INSERT INTO country VALUES (242, 'Zimbabwe');
